export const stageOrder = [
  'requirements',
  'data_collection',
  'data_preprocessing',
  'labeling',
  'model_design',
  'model_training',
  'validation',
  'deployment_ready',
  'operations_retro',
];

export const stageLabels = {
  requirements: '요구사항 분석',
  data_collection: '데이터 확보',
  data_preprocessing: '데이터 정제',
  labeling: '라벨링',
  model_design: '모델 설계',
  model_training: '모델 개발',
  validation: '검증',
  deployment_ready: '배포 준비',
  operations_retro: '운영/회고',
};

export const signalLabels = {
  requirement_defined: '요구사항 정의',
  scope_defined: '범위 정의',
  data_available: '데이터 확보',
  data_quality_valid: '데이터 품질',
  label_available: '라벨 확보',
  model_fixed: '모델 픽스',
  evaluation_defined: '평가 기준',
  customer_approved: '고객/내부 승인',
};

export const projects = [
  {
    id: 'p1',
    name: '한주라이트메탈',
    type: 'PoC',
    summary: '데이터 미확보 및 API 미정으로 PoC 진행 불가 상태',
    currentStage: 'data_collection',
    nextStage: 'data_preprocessing',
    stageEntryStatus: 'blocked',
    dataCoverage: 43,
    modelStatus: 'candidate_compare',
    modelFixed: false,
    pocReady: false,
    blockers: ['고객 데이터 미전달', 'API/PLC 연동 가능 여부 미확정', '평가 기준 없음'],
    warnings: ['요구사항 변경 후 일정 재산정 미실시'],
    nextDecisions: [
      '고객 데이터 요청 우선 진행 여부 결정',
      'PoC 범위를 1개 품목으로 축소할지 결정',
      '평가 기준 정의를 선행할지 결정',
    ],
    signals: {
      requirement_defined: true,
      scope_defined: false,
      data_available: false,
      data_quality_valid: false,
      label_available: false,
      model_fixed: false,
      evaluation_defined: false,
      customer_approved: false,
    },
    stages: [
      {
        stage: 'requirements',
        owner: '김PO',
        completionRate: 80,
        gateChecks: [
          {
            ruleCode: 'requirement_doc_exists',
            ruleName: '고객 요구사항 문서 등록',
            severity: 'blocker',
            required: true,
            passed: true,
            expected: '문서 1개 이상',
            actual: '요구사항 v0.9',
            recommendedAction: '최신 변경사항 반영 후 승인 요청',
          },
          {
            ruleCode: 'success_kpi_defined',
            ruleName: '성공 기준 등록',
            severity: 'blocker',
            required: true,
            passed: false,
            expected: 'KPI 3개 정의',
            actual: 'KPI 1개 정의',
            recommendedAction: '정확도/재현율/오검율 KPI 등록',
          },
        ],
      },
      {
        stage: 'data_collection',
        owner: '박DE',
        completionRate: 45,
        gateChecks: [
          {
            ruleCode: 'minimum_sample_count',
            ruleName: '최소 샘플 수 충족',
            severity: 'blocker',
            required: true,
            passed: false,
            expected: '샘플 >= 1000',
            actual: '샘플 520',
            recommendedAction: '샘플 480건 추가 확보',
          },
          {
            ruleCode: 'data_quality_checked',
            ruleName: '결측/품질 점검 완료',
            severity: 'warning',
            required: true,
            passed: false,
            expected: '품질 점수 >= 0.8',
            actual: '품질 점수 0.63',
            recommendedAction: '품질 검수 체크리스트 완료',
          },
        ],
      },
      {
        stage: 'model_training',
        owner: '최ML',
        completionRate: 20,
        gateChecks: [
          {
            ruleCode: 'baseline_secured',
            ruleName: '베이스라인 성능 확보',
            severity: 'warning',
            required: true,
            passed: false,
            expected: 'F1 >= 0.7',
            actual: 'F1 0.62',
            recommendedAction: '데이터 증강 + 하이퍼파라미터 튜닝',
          },
          {
            ruleCode: 'model_fixed',
            ruleName: '모델 픽스 여부 체크',
            severity: 'blocker',
            required: true,
            passed: false,
            expected: 'model_status == fixed',
            actual: 'candidate_compare',
            recommendedAction: '모델 비교표 생성 후 승인 요청',
          },
        ],
      },
    ],
    decisions: [
      {
        id: 'd1',
        title: 'PoC 보류',
        type: '일정',
        status: '승인',
        reason: '원본 데이터 미확보',
        impact: '검증 일정 1주 지연',
        approver: '사업총괄',
        date: '2026-03-29',
      },
      {
        id: 'd2',
        title: '데이터 추가 수집 여부',
        type: '데이터',
        status: '검토중',
        reason: '최소 샘플 수 미달',
        impact: '학습 일정 지연 가능',
        approver: '-',
        date: '2026-03-30',
      },
    ],
    docs: [
      { name: '요구사항 정의서 v0.9', type: '기획서', extracted: ['scope_defined=false'] },
      { name: '데이터 품질 리포트 v0.3', type: '검토서', extracted: ['data_quality_valid=false'] },
    ],
    alerts: [
      {
        id: 'a1',
        severity: 'blocker',
        title: '최소 학습 데이터 기준 미충족',
        message: '샘플 1000건 기준 대비 현재 520건',
        stage: 'data_collection',
        recommendedAction: '샘플 480건 추가 확보',
        status: 'open',
      },
      {
        id: 'a2',
        severity: 'warning',
        title: '요구사항 변경 후 일정 재산정 미실시',
        message: '3월 변경사항 반영 일정 없음',
        stage: 'requirements',
        recommendedAction: '일정 영향 분석 Agent 실행',
        status: 'open',
      },
      {
        id: 'a3',
        severity: 'info',
        title: '고객 피드백 반영 후보 3건 존재',
        message: '다음 스프린트 반영 검토 필요',
        stage: 'validation',
        recommendedAction: '의사결정 센터에서 우선순위 지정',
        status: 'open',
      },
    ],
    agentReviews: [
      {
        agent: 'Gate Review Agent',
        summary: '다음 단계 진입 불가',
        issues: ['최소 샘플 수 미달', '모델 픽스 미완료'],
        recommendations: ['샘플 480건 추가 확보', '모델 비교표 생성 및 승인 요청'],
        confidence: 0.93,
      },
      {
        agent: 'Schedule Impact Agent',
        summary: '데이터 추가 수집 필요 시 1주 지연 가능',
        issues: ['검증 일정 재조정 필요'],
        recommendations: ['고객 데모 일정 리스케줄 검토'],
        confidence: 0.88,
      },
    ],
  },
  {
    id: 'p2',
    name: 'IRIS 자동평가 고도화',
    type: 'Product',
    summary: '모델 검증 단계이며 실증 준비 가능 상태',
    currentStage: 'validation',
    nextStage: 'deployment_ready',
    stageEntryStatus: 'conditional',
    dataCoverage: 92,
    modelStatus: 'fixed',
    modelFixed: true,
    pocReady: true,
    blockers: [],
    warnings: ['고객 승인 전 최종 데모 일정 확정 필요'],
    nextDecisions: ['검증 데이터 추가 수집 여부 결정', '실증 범위 확정'],
    signals: {
      requirement_defined: true,
      scope_defined: true,
      data_available: true,
      data_quality_valid: true,
      label_available: true,
      model_fixed: true,
      evaluation_defined: true,
      customer_approved: false,
    },
    stages: [],
    decisions: [],
    docs: [],
    alerts: [
      {
        id: 'a4',
        severity: 'warning',
        title: '고객 승인 로그 누락',
        message: '배포 준비 단계 진입 전 승인 필요',
        stage: 'deployment_ready',
        recommendedAction: '고객 승인 회의록 업로드',
        status: 'open',
      },
    ],
    agentReviews: [],
  },
];

export const alertRules = [
  { no: 1, stage: 'requirements', severity: 'blocker', title: '요구사항 문서 미등록 상태에서 분석 완료 처리 시' },
  { no: 2, stage: 'requirements', severity: 'blocker', title: '성공 기준 KPI 미정 상태에서 프로젝트 착수 시' },
  { no: 3, stage: 'requirements', severity: 'warning', title: '요구사항 변경 발생 후 일정 재산정 미실시' },
  { no: 4, stage: 'data_collection', severity: 'blocker', title: '최소 데이터 수 미달 상태에서 모델 학습 진입' },
  { no: 5, stage: 'data_collection', severity: 'warning', title: '클래스 불균형 심각 상태에서 학습 진행' },
  { no: 6, stage: 'labeling', severity: 'blocker', title: '라벨 기준서 없이 라벨링 시작' },
  { no: 7, stage: 'data_collection', severity: 'warning', title: '데이터 품질 점검 없이 데이터 확보 완료 처리' },
  { no: 8, stage: 'validation', severity: 'blocker', title: 'Train/Val/Test 분리 없이 검증 단계 진입' },
  { no: 9, stage: 'model_design', severity: 'blocker', title: '문제 정의 미확정 상태에서 모델 설계 시작' },
  { no: 10, stage: 'model_training', severity: 'warning', title: '베이스라인 결과 없이 고도화 모델 개발 진행' },
  { no: 11, stage: 'validation', severity: 'blocker', title: '모델 후보 2개 이상인데 픽스 없이 검증 단계 진입' },
  { no: 12, stage: 'deployment_ready', severity: 'blocker', title: '운영 임계값 미설정 상태에서 배포 준비 전환' },
  { no: 13, stage: 'model_training', severity: 'warning', title: '재현 불가능 실험 결과를 기준으로 모델 확정 시도' },
  { no: 14, stage: 'validation', severity: 'warning', title: '검증 리포트 없이 고객 데모 일정 확정' },
  { no: 15, stage: 'validation', severity: 'warning', title: '현업 승인 없이 자동평가 결과 채택' },
  { no: 16, stage: 'deployment_ready', severity: 'blocker', title: '목표 KPI 미달인데 배포 승인 요청' },
  { no: 17, stage: 'operations_retro', severity: 'blocker', title: '핵심 산출물 누락 상태에서 단계 완료 처리' },
  { no: 18, stage: 'any', severity: 'blocker', title: 'Blocker 존재 상태에서 다음 단계 이동' },
  { no: 19, stage: 'any', severity: 'warning', title: '최근 7일간 의사결정 없이 태스크만 증가' },
  { no: 20, stage: 'deployment_ready', severity: 'warning', title: '고객 피드백 반영 여부 미정 상태로 릴리즈 준비' },
];
